# Generated by Django 3.2.25 on 2024-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240426_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_clearance',
            field=models.BooleanField(default=False, verbose_name='Clearance Item'),
        ),
    ]
